// src/seed-data.js
// Menu content transcribed from the restaurant's two current TV menu boards.
// This only runs ONCE, the first time the database is empty — after that,
// everything is managed from the admin panel, so editing this file later
// has no effect on a live install.

const BOARDS = [
  {
    slug: 'kahvalti-waffle-pancake',
    name: 'Breakfast, Waffles & Pancakes',
    subtitle: 'Board 1',
    template: 'breakfast-classic',
    rotation_seconds: 20,
    categories: [
      {
        name: 'Breakfast Plates',
        column_hint: 'plates',
        items: [
          { display_name: 'Turkish Breakfast Plate', price: 17, description: 'Simit (Turkish sesame bagel), 2 fresh cracked eggs, cream cheese, feta cheese, fresh mozzarella, olive, tomato, walnut, honey, jam, butter, spring mix, fresh fruit, cucumber, toast.' },
          { display_name: 'Combo Breakfast Plate', price: 15, description: '2 fresh cracked eggs of any style, 2 all natural turkey bacon, homefries and 2 toast served with tomatoes, cucumber, spring mix, butter and jam.' },
          { display_name: 'Egg Plate', price: 12.49, description: '2 fresh cracked eggs, 2 all natural turkey bacon & 2 toast with tomatoes, cucumber, spring mix, jam, butter.' },
          { display_name: 'Simit Plate', price: 12.49, description: 'Simit (Turkish sesame bagel), spring mix, tomatoes, cucumber, 2 fresh cracked eggs with cheese and olives.' },
          { display_name: 'Borek Plate', price: 12.49, description: 'Spinach & Feta borek, spring mix, tomatoes, cucumber, 2 fresh cracked eggs with cheese and olives.' },
          { display_name: 'Gozleme Plate', price: 13.49, description: 'Mediterranean mozzarella or ground beef stuffed flatbread served with spring mix, tomatoes, cucumber and olives.' },
        ],
      },
      {
        name: 'French Toast',
        column_hint: 'french-toast',
        items: [
          { display_name: 'Nutella Stuffed French Toast', price: 13, description: 'Nutella stuffed Challah bread dipped in homemade batter with fresh strawberry, blueberry and banana. Topped with powder sugar and syrup.' },
          { display_name: 'French Toast BEC', price: 13, description: 'Challah bread dipped in homemade batter w/ 2 all natural turkey bacon, 2 fresh cracked eggs and american cheese on top, and syrup.' },
          { display_name: 'French Toast Whip Berry', price: 13, description: 'Challah bread dipped in homemade batter served with berries, whipped cream and berry drizzle.' },
          { display_name: 'French Toast W/Fruits', price: 12, description: 'Challah bread dipped in homemade batter served with fresh fruit, whipped cream and syrup.' },
          { display_name: 'Monte Cristo French Toast', price: 16, description: 'Challah bread dipped in house made batter with roasted turkey and cheddar cheese. Served with strawberry jam.' },
          { display_name: 'Strawberry Cheesecake French Toast', price: 16, description: 'Thick cut French toast with spread of whipped cream cheese, topped with fresh strawberries, white chocolate chips, berry sauce and side of syrup.' },
        ],
      },
      {
        name: 'Appetizers & Sides',
        note: 'Sides are only sold with a main item and cannot be ordered individually.',
        column_hint: 'sides-dark',
        items: [
          { display_name: 'Homefries', price: 5 },
          { display_name: 'Simit (Turkish Bagel)', price: 3.5 },
          { display_name: 'Organic Pure Maple Syrup', price: 2 },
          { display_name: 'Borek (Feta & Spinach)', price: 5.49 },
          { display_name: '2 Turkey Bacon', price: 3 },
          { display_name: '2 Eggs', price: 3.5 },
          { display_name: 'Turkey Sausage', price: 3 },
        ],
      },
      {
        name: 'Gourmet Brussels Waffles',
        note: 'HOUSE MADE BATTER — we don’t use any kind of instant waffle mix. We make our own waffle batter fresh from scratch every day.',
        column_hint: 'waffle-1',
        items: [
          { display_name: 'Strawberry Nutella Waffle', price: 10.99, description: 'Nutella chocolate and strawberries on the Fresh Pressed Artisan Brussels Waffle.' },
          { display_name: 'Whipped Berry Waffle', price: 11.99, description: 'Strawberry, blueberry, our special whipped cream, berry drizzle.' },
          { display_name: 'Hazelnut Nutella Waffle', price: 10.99, description: 'Nutella and Turkish hazelnut on the Fresh Pressed Artisan Brussels Waffle.' },
          { display_name: 'Parisienne Waffle', price: 11.99, description: 'Our special whipped cream, fresh strawberries, blueberries, chocolate sauce with powder sugar.' },
          { display_name: 'Banana Nutella Waffle', price: 10.99, description: 'Nutella chocolate sauce and banana on the Fresh Pressed Artisan Brussels Waffle.' },
          { display_name: 'Strawberry Cheesecake Waffle', price: 12.99, description: 'Our special whipped cream, fresh strawberries, strawberry jam, graham cracker crunch, white chocolate chips.' },
          { display_name: 'Cinnamon Crunch Waffle', price: 11.99, description: 'Our special whipped cream, Cinnamon Toast Crunch, white chocolate chips, caramel sauce.' },
        ],
      },
      {
        name: 'Gourmet Brussels Waffles',
        column_hint: 'waffle-2',
        items: [
          { display_name: 'Waffle Street Special', price: 12.99, description: 'Fresh banana, strawberry, kiwi, hazelnut, pistachio with nutella chocolate or peanut sauce.' },
          { display_name: 'Elvis Style Waffle', price: 12.99, description: 'Peanut sauce, banana, syrup and 2 all natural turkey bacon on the Fresh Artisan Waffle.' },
          { display_name: 'Whipped Caramel Banana', price: 11.99, description: 'Our special whipped cream, banana, and caramel sauce.' },
          { display_name: 'French Waffle', price: 11.99, description: 'Whipped cream, strawberry and banana, syrup with cinnamon.' },
          { display_name: 'Aloha Waffle', price: 11.99, description: 'Kiwi, pineapple, banana, syrup with our special whipped cream on the Fresh Artisan Waffle.' },
          { display_name: 'Oreo Waffle', price: 11.99, description: 'Whipped vanilla cream icing, Oreo pieces, chocolate sauce, powder sugar on Waffle.' },
          { display_name: 'Bacon, Egg and Cheese', price: 12.99, description: '2 fresh cracked eggs, 2 all natural turkey bacon with your choice of cheese.', badges: ['egg'] },
        ],
      },
      {
        name: 'Pancake Plates',
        note: 'Make Full Stack +$5',
        column_hint: 'pancakes',
        items: [
          { display_name: 'Classic Pancake', price: 9.99, description: 'Short stack fluffy homemade buttermilk pancakes w/syrup and butter.' },
          { display_name: 'Berry Pancake', price: 12.99, description: 'Short stack fluffy homemade buttermilk pancakes filled with blueberry, topped blueberry and strawberry, whip cream.' },
          { display_name: 'Strawberry Banana Pancake', price: 13.99, description: 'Short stack fluffy homemade buttermilk pancakes topped with fresh strawberry, banana, whip cream.' },
          { display_name: 'Chocolate Chip Pancake', price: 12.99, description: 'Short stack fluffy homemade buttermilk pancakes filled with chocolate chip, topped chocolate syrup and chocolate chips.' },
          { display_name: 'Classic Breakfast Pancake', price: 13.99, description: 'Short stack fluffy homemade buttermilk pancakes with 2 all natural turkey bacon, 2 fresh cracked eggs, syrup and butter.' },
          { display_name: 'Combo Breakfast Pancake', price: 15.99, description: 'Short stack fluffy homemade buttermilk pancakes with 2 fresh cracked eggs, 2 all natural turkey bacon, homefries, syrup and butter.' },
        ],
      },
      {
        name: 'Salads',
        note: 'Add Chicken +$4 — choose your dressing: balsamic, ranch, italian dressing, olive oil.',
        column_hint: 'salads',
        items: [
          { display_name: 'Protein Power Salad', price: 13, description: 'Spring mix, boiled egg, tomato, carrot, red cabbage, cucumber, feta cheese, walnut.' },
          { display_name: 'Mediterranean Mix', price: 13, description: 'Lettuce & spring mix, tomato, cucumber, olive, red cabbage, feta cheese, fajita greens, pickled onion.' },
          { display_name: 'Red and Green Salad', price: 12, description: 'Organic baby spinach, fresh strawberries, tomato, cucumber, feta, pecan.' },
          { display_name: 'Grilled Chicken Salad', price: 14, description: 'Spring mix & lettuce, grilled chicken, chickpeas, tomato, cucumber, carrot, pickled onion, fajita greens.' },
          { display_name: 'Fresh Garden', price: 10, description: 'Lettuce & spring mix, tomato, cucumber, carrot, pickled onion.' },
        ],
      },
    ],
  },
  {
    slug: 'sandwiches-pastries-drinks',
    name: 'Signature Sandwiches, Pastries & Drinks',
    subtitle: 'Board 2',
    template: 'sandwich-classic',
    rotation_seconds: 20,
    categories: [
      {
        name: "Mumu's Homemade Pastries",
        note: 'The stock status of the products is variable.',
        column_hint: 'pastries',
        items: [
          { display_name: 'Cakes & Pie Slices', price: 6.5, description: 'Opera Cake, Tiramisu, Pumpkin Cake, Chocolate Cake, Carrot Cake, Tres Leches, Apple Pie, Burnt Basque Cheesecake, Baklava, Sekerpare.' },
          { display_name: 'Muffin', price: 3.49, description: 'Blueberry, Double Chocolate, Banana Nut.' },
        ],
      },
      {
        name: 'Hand Crafted Pudding Cups',
        column_hint: 'puddings',
        items: [
          { display_name: 'Banana Pudding', price: 7.99 },
          { display_name: 'Blueberry Pudding', price: 7.99 },
          { display_name: 'Pistachio Pudding', price: 7.99 },
          { display_name: 'Hazelnut Pudding', price: 7.99 },
          { display_name: 'Strawberry Pudding', price: 7.99 },
          { display_name: 'Oreo Pudding', price: 7.99 },
          { display_name: 'Parfait Cup', price: 6.99 },
          { display_name: 'Fresh Fruit Cup', price: 5.99, price_suffix: '(12oz +$2)' },
        ],
      },
      {
        name: 'Hot and Cold Drinks',
        column_hint: 'drinks',
        items: [
          { display_name: 'Can Soda', price: 2, description: 'Pepsi, Diet Pepsi, Ginger Ale, Brisk Iced Tea.' },
          { display_name: 'Juice', price: 3, description: 'Orange, Apple, Lemonade.' },
          { display_name: 'San Pellegrino', price: 3, description: 'Orange, Blood Orange, Pomegranate, Lemon.' },
          { display_name: 'Celsius', price: 4 },
          { display_name: 'Iced Coffee', price: 3 },
          { display_name: 'Bottle Water', price: 2 },
          { display_name: 'Hot Tea', price: 3, description: 'Black Tea, Earl Grey, Orange Spice, Lemon Ginger, Raspberry Pomegranate, Green Tea, Winter Tea (Special Blend $5).' },
          { display_name: 'Hot Coffee', price: 3, description: 'Dark Roast Coffee. Flavors: Vanilla, Caramel.' },
          { display_name: 'Turkish Coffee', price: 5 },
        ],
      },
      {
        name: 'Croissant & Bagel',
        note: 'Choose your bread: Plain / Everything Bagel or Croissant.',
        column_hint: 'sandwich-1',
        items: [
          { display_name: 'Egg and Cheese', price: 6.99, description: 'Scrambled egg, cheese. Add+ guacamole +$2, turkey bacon +$1, turkey sausage +$2.', badges: ['egg'] },
          { display_name: 'Vegetarian Breakfast', price: 9.99, description: 'Scrambled eggs, American cheese, baby spinach, tomato, walnut.', badges: ['egg'] },
          { display_name: 'Istanbul', price: 9.99, description: 'Spring mix greens, basil pesto, fresh mozzarella, tomatoes, olive pesto. Add+ guacamole +$1, egg +$1.', badges: ['vegetarian'] },
          { display_name: 'Western', price: 9.99, description: 'Egg, 2 all natural turkey bacon, roasted red pepper, cream cheese, onion.', badges: ['egg'] },
          { display_name: 'Fried Chicken', price: 9.99, description: 'Crispy chicken tender, pickles, tomatoes, arugula.' },
          { display_name: '3 Chocolate Croissant Box', price: 10.99, description: 'Strawberry, Banana, Nutella.' },
          { display_name: 'Elvis Style', price: 9.99, description: 'Peanut butter, bananas and 2 all natural turkey bacon.' },
          { display_name: 'BLT Sandwich', price: 7.99, description: 'All natural turkey bacon, arugula and tomatoes.' },
          { display_name: 'Adirondack', price: 10.99, description: 'Roasted turkey, roasted red pepper, basil pesto, american cheese, walnut.' },
          { display_name: 'Farmers Breakfast', price: 11.99, description: 'Tomatoes, arugula, cucumber, guacamole, fresh mozzarella, roasted turkey. Add+ egg +$1.' },
          { display_name: "Mumu's Breakfast", price: 7.99, description: 'American cheese, cream cheese, pepperjack cheese, basil pesto sauce, tomato and greens.', badges: ['vegetarian'] },
          { display_name: 'Chicken Salad', price: 10.99, description: 'Chicken salad with cranberry and pecan, tomatoes, organic spring mix.' },
        ],
      },
      {
        name: 'Wrap',
        note: 'Choose your wrap: White flour / Garlic / Wheat.',
        column_hint: 'sandwich-2',
        items: [
          { display_name: 'Bacon, Egg and Cheese', price: 9.99, description: 'Turkey bacon, scrambled egg, cheese. Add+ guacamole +$1.', badges: ['egg'] },
          { display_name: 'Turkish Style', price: 10.99, description: 'Feta cheese, tomato, American cheese, olive pesto, egg, Sucuk (Turkish pepperoni).', badges: ['halal', 'egg'] },
          { display_name: 'Vegetarian Breakfast', price: 10.99, description: '2 eggs, mixed cheese, organic baby spinach, tomato, walnut.', badges: ['egg'] },
          { display_name: 'Boombastic Breakfast', price: 12.99, description: '2 fresh cracked eggs, home fries, mixed cheese, feta, tomato, all natural turkey bacon, basil pesto, olive pesto, roasted red pepper.' },
          { display_name: "Mum's Combo Breakfast", price: 12.99, description: '2 fresh cracked eggs, home fries, mixed cheese, all natural turkey bacon, tomato, olive pesto.', badges: ['egg'] },
          { display_name: 'Chicken Salad', price: 11.99, description: 'Chicken salad with cranberry and pecan, tomatoes, arugula.' },
          { display_name: 'Veggie Pesto', price: 10.99, description: 'Roasted red pepper, arugula, artichoke and spinach creamy dip, fresh mozzarella, basil pesto.', badges: ['vegetarian'] },
          { display_name: 'Grilled Chicken', price: 12.99, description: 'Grilled chicken, home fries, mayo, arugula, onion, tomatoes, american cheese.', badges: ['halal'] },
          { display_name: 'Meatball (Kofta)', price: 12.99, description: 'Handcrafted kofta, home fries, mayo, arugula, onion, tomatoes, american cheese.', badges: ['halal'] },
        ],
      },
      {
        name: 'Panini',
        note: 'Panini served in sourdough bread with a side of black olives.',
        column_hint: 'sandwich-3',
        items: [
          { display_name: 'Turkey Guacamole', price: 11.99, description: 'Roasted turkey, provolone, tomato, basil pesto, guacamole.' },
          { display_name: 'Artichoke and Spinach', price: 11.99, description: 'Artichoke and spinach creamy dip, american cheese, basil pesto, roasted red pepper, all natural turkey bacon.' },
          { display_name: 'Roasted Turkey', price: 11.99, description: 'Roasted turkey, roasted red pepper, basil pesto, american cheese, walnut.' },
          { display_name: 'Buffalo Chicken', price: 12.99, description: 'Grilled chicken, all natural turkey bacon, spinach, buffalo hot sauce, pepperjack cheese.', badges: ['spicy'] },
          { display_name: 'Chipotle Chicken', price: 12.99, description: 'Grilled chicken, spinach, tomato, chipotle sauce, fresh mozzarella.', badges: ['spicy'] },
          { display_name: 'Chicken Pesto', price: 12.99, description: 'Grilled chicken, basil pesto, mayo, arugula, onion, roasted red pepper, american cheese.' },
          { display_name: 'Caprese', price: 11.99, description: 'Arugula, basil pesto, fresh mozzarella, tomatoes, olive pesto, walnut, balsamic.', badges: ['vegetarian'] },
          { display_name: 'Kofta (Turkish Meatball)', price: 12.99, description: 'Turkish meatballs, red onion, arugula, tomatoes, provolone cheese, roasted red pepper.', badges: ['halal'] },
          { display_name: 'Fireball', price: 12.99, description: 'Handcrafted kofta, all natural turkey bacon, spinach, hot sauce, roasted red pepper, pepper jack, jalapeno.', badges: ['double_spicy'] },
          { display_name: 'Veggie Pesto', price: 11.99, description: 'Roasted red pepper, artichoke and spinach creamy dip, fresh mozzarella, basil pesto.', badges: ['vegetarian'] },
          { display_name: 'Turkish Style', price: 11.99, description: 'Feta cheese, tomato, American cheese, olive pesto, egg, Sucuk (Turkish pepperoni).', badges: ['halal', 'egg'] },
        ],
      },
    ],
  },
];

module.exports = { BOARDS };
